services:
  database:
    image: postgres:16
    environment:
      POSTGRES_DB: leavetracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    user: root
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@electobox.com
      PGADMIN_DEFAULT_PASSWORD: tracker
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5478:80
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    depends_on:
      - database

volumes:
  postgres-volume:
  pgadmin-volume: